# espanso configuration file

# official documentation: https://espanso.org/docs

# Hide menu bar icon
show_icon: false

matches:
  # Planning & task management
  - trigger: ",fu"
    replace: "Follow up re: "
  - trigger: ",kr"
    replace: "Kind regards,"
  - trigger: ",mt"
    replace: "Many thanks,"
  - trigger: ",pe"
    replace: "Process email re: "
  - trigger: ",rr"
    replace: "Review and respond to "
  - trigger: ",pp"
    replace: "Plan new project: "
  - trigger: ",sm"
    replace: "Set meeting with
  - trigger: ",re"
    replace: "Respond to email re: "
  - trigger: ",co"
    replace: "Check out "
  - trigger: ",lc"
    replace: "(last check in: {{last_date}})"
    vars:
      - name: last_date
        type: date
        params:
          format: "%d-%m-%Y"

  # git-specific snippets
  - trigger: ",gp"
    replace: "git push origin HEAD"
  - trigger: ",gf"
    replace: "git checkout -b feature/"

  # Shell command example
  - trigger: ",shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

