matches:
  # Planning & task management
  - trigger: ",fu"
    replace: "Follow up re: "
  - trigger: ",kr"
    replace: "Kind regards,"
  - trigger: ",mt"
    replace: "Many thanks,"
  - trigger: ",pe"
    replace: "Process email re: "
  - trigger: ",rr"
    replace: "Review and respond to "
  - trigger: ",pp"
    replace: "Plan new project: "
  - trigger: ",am"
    replace: "Arrange meeting with "
  - trigger: ",re"
    replace: "Respond to email re: "
  - trigger: ",co"
    replace: "Check out "
  - trigger: ",wc"
    replace: "Waiting for call from "
  - trigger: ",lc"
    replace: "(last check in: {{last_date}})"
    vars:
      - name: last_date
        type: date
        params:
          format: "%d-%m-%Y"

  # git-specific snippets
  - trigger: ",gp"
    replace: "git push origin HEAD"
  - trigger: ",gb"
    replace: "git checkout -b feature/"
  - trigger: ",gc"
    replace: "git commit -m \""
  - trigger: ",ga"
    replace: "git add "
  - trigger: ",gl"
    replace: "git log"
  - trigger: ",gs"
    replace: "git status"
  - trigger: ",gd"
    replace: "git diff"
  - trigger: ",gm"
    replace: "git checkout main; git pull"
  - trigger: ",gr"
    replace: "git rebase main"
